name: coolsite 2
favicon: null
layout_spectrum: 0.46187
typography_spectrum: 0.22011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#da6142'
    - '#4d73c6'
    - '#203f80'
    - '#f4caa4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
